### ISSUE TITLE
Something is strange with the gem at rubygems.org

### ISSUE THREAD

**Issue by netzpirat** [tomharris/random_data#1]
When I install the random_data gem with Bundler fresh from RubyGems.org under Ruby 1.9.2 I get the following error: 
_random_data-1.5.1/lib/random_data/locations.rb:97: invalid multibyte char (US-ASCII)_

This issue has been resolved on 2009-06-27 with the following commit: http://github.com/tomharris/random_data/commit/db0d1ade1f095d41b3f8449c7dcc83a45a80d874

However, when I look directly at location.rb, there is **no encoding header** at the top of the file.

Random_data version 1.5.1 was released on 2010-01-18, so the commit that fixes the problem should be included within this gem, but it is not!

Can you please push an actual version to rubygems with the correct encoding header in location.rb?

Thank you for this great gem.
Michael

**Comment by tomharris** [comment]
Someone else beat me to uploading the gem to rubygems when they first launched. That guy never pulled in my patches and seems to have deleted his repo too. There's really nothing I can do.

To get around this, I am doing the following in my gemfile:
gem 'random_data', :git => 'git://github.com/tomharris/random_data.git'

Hope that helps.

**Comment by netzpirat** [comment]
Thanks for the fast response. I try to get in contact with that other person so he can add you as author and you can push it to rubygems.

**Comment by netzpirat** [comment]
You are now officially the owner of your gem ;-) Are you so kind to release a new version that contains the fixes on master also?

Many thanks

**Comment by tomharris** [comment]
Version 1.5.2 should be available on rubygems.

Thanks for your interest!

**Comment by netzpirat** [comment]
This is great! Thank you very much.
