### ISSUE TITLE
Random.state private

### ISSUE THREAD

**Issue by antarr** [tomharris/random_data#7]
When trying to use Random.state I get an exception saying 'attempted to access private method 'Random.state'

``` ruby
def fake_members
    if Member.count < 5
      start = 0
      max = 24

      while start < max
        member = Member.new(first_name: Random.firstname, last_name: Random.lastname, address: Random.address_line_1,
                            city: Random.city, state:  Random.state , zipcode: Random.zipcode, phone_number: Random.phone,
                            email: Random.email)
        member.save
        start += 1
      end
    end
  end
```

**Comment by tomharris** [comment]
Random.state is a built-in private method in ruby 1.9. Use the alias Random.state_code instead.

I'm about push out a new gem that removes .state and references to it in the docs. It's been deprecated for a while, but I think it's finally time as most people are on 1.9 now.

Thanks for opening the issue!
